import React from 'react'
import Head from 'next/head'

//components
import Sidebar from '../components/sidebar'

export default function layout(props) {
  return (
    <>
       <Head>
        <title>Radar Creators</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

        <div className='flex'>
            <Sidebar />
            <div className='px-7 py-8 flex-1 h-screen bg-slate-100'>
                <main>{props.children}</main>
            </div>
        </div>
    </>
  )
}

